/// Flutter icons CrustCons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CrustCons
///      fonts:
///       - asset: fonts/CrustCons.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
///
import 'package:flutter/widgets.dart';

class CrustCons {
  CrustCons._();

  static const _kFontFam = 'CrustCons';

  static const IconData back = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData new_post = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData paper_plane = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData person = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData present = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData triple_dot = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData padlock = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData bread_heart = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData bubble_heart = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData camera = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData logout = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData view_mode = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData menu_bold = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData qr = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData location = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData location_bold_1 = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData phone_bold = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData location_bold = const IconData(0xe822, fontFamily: _kFontFam);
  static const IconData post_comment = const IconData(0xe823, fontFamily: _kFontFam);
  static const IconData call_bold = const IconData(0xe824, fontFamily: _kFontFam);
}
