/// Flutter icons CrustCon
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CrustCon
///      fonts:
///       - asset: fonts/CrustCon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CrustCon {
  CrustCon._();

  static const _kFontFam = 'CrustCon';

  static const IconData bubble_heart = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData camera = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData logout = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData new_post = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData paper_plane = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData present = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xe808, fontFamily: _kFontFam);
}
